version: "3.8" # 19.03.0+
services:
  app:
    image: fermium-alpine3.11
    container_name: test-node-dev
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/src
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13-alpine
    restart: always
    env_file: ./.env
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432 # Can be closed for prod
