version: "3.8" # 19.03.0+
services:
  app:
    image: fermium-alpine3.11
    container_name: test-node-dev
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/src
