# serverless.yml

service: video-downloader-serverless

provider:
  name: aws

  runtime: nodejs12.x

  stage: dev

  region: eu-central-1

functions:
  app:
    handler: "./src/serverless.handler"
    environment:
      NODE_ENV: dev
    events:
      - http: ANY /
      - http: "ANY /{proxy+}"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true #Fixes root route problem
    httpPort: 5000
